import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import LoadingWrapper from "@/components/LoadingWrapper"




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-lora font-normal antialiased`}
      >
        <LoadingWrapper>
          <NavBar />
          {children}
          <Footer />
        </LoadingWrapper>
      </body>
    </html>
  );
}
