import { iPropertyData } from "@/types/types";

 // eslint-disable-next-line @typescript-eslint/no-unused-vars
 interface icarousalData {
  image:string;
  subtitle?:string;
  title?:string;
  price?:string;
  link?:string;
 }
export const carouselData = [
    {
      image: "/exclusive/bvlgari/1.webp",
      subtitle: "Bvlgari Resorts & Hotel",
      title: "Bvlgari Mansion",
      price: "AED 495,000,000",
      link: "exclusive/Bvlgari.html",
    },
    {
      image: "/exclusive/j20/images/home.webp",
      subtitle: "Palm Jumeirah",
      title: "Custom-built Signature Villa",
      price: "AED 250,000,000",
      link: "exclusive/Villa Frond J.html",
    },
    {
      image: "/exclusive/Ocean Mansion/images/EXTERIOR_3-2.webp",
      subtitle: "Bvlgari Resorts & Hotel",
      title: "Bvlgari Ocean Mansion",
      price: "AED 180,000,000",
      link: "exclusive/ocean mansion.html",
    },
    {
      image: "/exclusive/g11/images/home.png",
      subtitle: "Palm Jumeirah",
      title: "Billionaires’ Row Signature Villa",
      price: "AED 165,000,000",
      link: "exclusive/La Solaro.html",
    },
    {
      image: "/exclusive/Villa Palm/images/home.webp",
      subtitle: "Palm Jumeirah",
      title: "Modern Garden Villa",
      price: "Price Upon Request",
      link: "exclusive/Villa Palm.html",
    },
    {
      image: "/exclusive/Villa Frond A/images/1.webp",
      subtitle: "Palm Jumeirah",
      title: "Signature Villa",
      price: "AED 135,000,000",
      link: "exclusive/Villa Frond A.html",
    },
    {
      image: "/exclusive/Villa Frond L/images/36-2.webp",
      subtitle: "Palm Jumeirah",
      title: "Villa Frond L",
      price: "AED 65,000,000",
      link: "exclusive/Villa Frond L.html",
    },
    {
      image: "/exclusive/Mansion Al Barari/images/0.png",
      subtitle: "Al Barari",
      title: "Mansion Al Barari",
      price: "AED 75,000,000",
      link: "exclusive/mansion al barari.html",
    }
  ];


  export const exampleProperty: iPropertyData[] = [
  {
    id: "villa-123",
    title: "Custom-Built Signature Villa",
    location: "Palm Jumeirah, Dubai",
    price: 250000000,
    currency: "AED",
    bedrooms: 5,
    bathrooms: 7,
    squareFootage: 15190.3,
    squareFootageUnit: "Sq.Ft",
    images: [
      "/exclusive/j20/images/0.png",
      "/exclusive/j20/images/bath1.webp",
      "/exclusive/j20/images/bed 1.webp",
      "/exclusive/j20/images/cinema.webp",
      "/exclusive/j20/images/dining formal.webp",
      "/exclusive/j20/images/gym.webp",
    ],
    featured: true,
    href: "/property/custom-built-signature-villa",
  },
  {
    id: "billionaires-row",
    title: "Billionaires Row Signature Villa",
    location: "Dubai Marina, Dubai",
    price: 150000000,
    currency: "AED",
    bedrooms: 6,
    bathrooms: 8,
    squareFootage: 12000,
    squareFootageUnit: "Sq.Ft",
    images: [
      "/exclusive/g11/images/home.png",
      "/exclusive/g11/images/1.webp",
      "/exclusive/g11/images/2.webp",
      "/exclusive/g11/images/3.webp",
      "/exclusive/g11/images/4.webp",
      "/exclusive/g11/images/5.webp",
    ],
    featured: false,
    href: "/property/luxury-villa",
  },
  {
    id: "palm-villa-456",
    title: "Custom-Built Signature Villa",
    location: "Palm Jumeirah, Dubai",
    price: 250000000,
    currency: "AED",
    bedrooms: 5,
    bathrooms: 7,
    squareFootage: 15190.3,
    squareFootageUnit: "Sq.Ft",
    images: [
      "/exclusive/j20/images/0.png",
      "/exclusive/j20/images/bath1.webp",
      "/exclusive/j20/images/bed 1.webp",
      "/exclusive/j20/images/cinema.webp",
      "/exclusive/j20/images/dining formal.webp",
      "/exclusive/j20/images/gym.webp",
    ],
    featured: true,
    href: "/property/custom-built-signature-villa",
  },
  {
    id: "villa-123",
    title: "Custom-Built Signature Villa",
    location: "Palm Jumeirah, Dubai",
    price: 250000000,
    currency: "AED",
    bedrooms: 5,
    bathrooms: 7,
    squareFootage: 15190.3,
    squareFootageUnit: "Sq.Ft",
    images: [
      "/exclusive/j20/images/0.png",
      "/exclusive/j20/images/bath1.webp",
      "/exclusive/j20/images/bed 1.webp",
      "/exclusive/j20/images/cinema.webp",
      "/exclusive/j20/images/dining formal.webp",
      "/exclusive/j20/images/gym.webp",
    ],
    featured: true,
    href: "/property/custom-built-signature-villa",
  },
  {
    id: "billionaires-row",
    title: "Billionaires Row Signature Villa",
    location: "Dubai Marina, Dubai",
    price: 150000000,
    currency: "AED",
    bedrooms: 6,
    bathrooms: 8,
    squareFootage: 12000,
    squareFootageUnit: "Sq.Ft",
    images: [
      "/exclusive/g11/images/home.png",
      "/exclusive/g11/images/1.webp",
      "/exclusive/g11/images/2.webp",
      "/exclusive/g11/images/3.webp",
      "/exclusive/g11/images/4.webp",
      "/exclusive/g11/images/5.webp",
    ],
    featured: false,
    href: "/property/luxury-villa",
  },
  {
    id: "palm-villa-456",
    title: "Custom-Built Signature Villa",
    location: "Palm Jumeirah, Dubai",
    price: 250000000,
    currency: "AED",
    bedrooms: 5,
    bathrooms: 7,
    squareFootage: 15190.3,
    squareFootageUnit: "Sq.Ft",
    images: [
      "/exclusive/j20/images/0.png",
      "/exclusive/j20/images/bath1.webp",
      "/exclusive/j20/images/bed 1.webp",
      "/exclusive/j20/images/cinema.webp",
      "/exclusive/j20/images/dining formal.webp",
      "/exclusive/j20/images/gym.webp",
    ],
    featured: true,
    href: "/property/custom-built-signature-villa",
  },
  {
    id: "billionaires-row",
    title: "Billionaires Row Signature Villa",
    location: "Dubai Marina, Dubai",
    price: 150000000,
    currency: "AED",
    bedrooms: 6,
    bathrooms: 8,
    squareFootage: 12000,
    squareFootageUnit: "Sq.Ft",
    images: [
      "/exclusive/g11/images/home.png",
      "/exclusive/g11/images/1.webp",
      "/exclusive/g11/images/2.webp",
      "/exclusive/g11/images/3.webp",
      "/exclusive/g11/images/4.webp",
      "/exclusive/g11/images/5.webp",
    ],
    featured: false,
    href: "/property/luxury-villa",
  },
  {
    id: "palm-villa-456",
    title: "Custom-Built Signature Villa",
    location: "Palm Jumeirah, Dubai",
    price: 250000000,
    currency: "AED",
    bedrooms: 5,
    bathrooms: 7,
    squareFootage: 15190.3,
    squareFootageUnit: "Sq.Ft",
    images: [
      "/exclusive/j20/images/0.png",
      "/exclusive/j20/images/bath1.webp",
      "/exclusive/j20/images/bed 1.webp",
      "/exclusive/j20/images/cinema.webp",
      "/exclusive/j20/images/dining formal.webp",
      "/exclusive/j20/images/gym.webp",
    ],
    featured: true,
    href: "/property/custom-built-signature-villa",
  },
  {
    id: "billionaires-row",
    title: "Billionaires Row Signature Villa",
    location: "Dubai Marina, Dubai",
    price: 150000000,
    currency: "AED",
    bedrooms: 6,
    bathrooms: 8,
    squareFootage: 12000,
    squareFootageUnit: "Sq.Ft",
    images: [
      "/exclusive/g11/images/home.png",
      "/exclusive/g11/images/1.webp",
      "/exclusive/g11/images/2.webp",
      "/exclusive/g11/images/3.webp",
      "/exclusive/g11/images/4.webp",
      "/exclusive/g11/images/5.webp",
    ],
    featured: false,
    href: "/property/luxury-villa",
  },
  {
    id: "palm-villa-456",
    title: "Custom-Built Signature Villa",
    location: "Palm Jumeirah, Dubai",
    price: 250000000,
    currency: "AED",
    bedrooms: 5,
    bathrooms: 7,
    squareFootage: 15190.3,
    squareFootageUnit: "Sq.Ft",
    images: [
      "/exclusive/j20/images/0.png",
      "/exclusive/j20/images/bath1.webp",
      "/exclusive/j20/images/bed 1.webp",
      "/exclusive/j20/images/cinema.webp",
      "/exclusive/j20/images/dining formal.webp",
      "/exclusive/j20/images/gym.webp",
    ],
    featured: true,
    href: "/property/custom-built-signature-villa",
  },
  {
    id: "billionaires-row",
    title: "Billionaires Row Signature Villa",
    location: "Dubai Marina, Dubai",
    price: 150000000,
    currency: "AED",
    bedrooms: 6,
    bathrooms: 8,
    squareFootage: 12000,
    squareFootageUnit: "Sq.Ft",
    images: [
      "/exclusive/g11/images/home.png",
      "/exclusive/g11/images/1.webp",
      "/exclusive/g11/images/2.webp",
      "/exclusive/g11/images/3.webp",
      "/exclusive/g11/images/4.webp",
      "/exclusive/g11/images/5.webp",
    ],
    featured: false,
    href: "/property/luxury-villa",
  },
  {
    id: "palm-villa-456",
    title: "Custom-Built Signature Villa",
    location: "Palm Jumeirah, Dubai",
    price: 250000000,
    currency: "AED",
    bedrooms: 5,
    bathrooms: 7,
    squareFootage: 15190.3,
    squareFootageUnit: "Sq.Ft",
    images: [
      "/exclusive/j20/images/0.png",
      "/exclusive/j20/images/bath1.webp",
      "/exclusive/j20/images/bed 1.webp",
      "/exclusive/j20/images/cinema.webp",
      "/exclusive/j20/images/dining formal.webp",
      "/exclusive/j20/images/gym.webp",
    ],
    featured: true,
    href: "/property/custom-built-signature-villa",
  },
  {
    id: "villa-123",
    title: "Custom-Built Signature Villa",
    location: "Palm Jumeirah, Dubai",
    price: 250000000,
    currency: "AED",
    bedrooms: 5,
    bathrooms: 7,
    squareFootage: 15190.3,
    squareFootageUnit: "Sq.Ft",
    images: [
      "/exclusive/j20/images/0.png",
      "/exclusive/j20/images/bath1.webp",
      "/exclusive/j20/images/bed 1.webp",
      "/exclusive/j20/images/cinema.webp",
      "/exclusive/j20/images/dining formal.webp",
      "/exclusive/j20/images/gym.webp",
    ],
    featured: true,
    href: "/property/custom-built-signature-villa",
  },
  {
    id: "billionaires-row",
    title: "Billionaires Row Signature Villa",
    location: "Dubai Marina, Dubai",
    price: 150000000,
    currency: "AED",
    bedrooms: 6,
    bathrooms: 8,
    squareFootage: 12000,
    squareFootageUnit: "Sq.Ft",
    images: [
      "/exclusive/g11/images/home.png",
      "/exclusive/g11/images/1.webp",
      "/exclusive/g11/images/2.webp",
      "/exclusive/g11/images/3.webp",
      "/exclusive/g11/images/4.webp",
      "/exclusive/g11/images/5.webp",
    ],
    featured: false,
    href: "/property/luxury-villa",
  },
  {
    id: "palm-villa-456",
    title: "Custom-Built Signature Villa",
    location: "Palm Jumeirah, Dubai",
    price: 250000000,
    currency: "AED",
    bedrooms: 5,
    bathrooms: 7,
    squareFootage: 15190.3,
    squareFootageUnit: "Sq.Ft",
    images: [
      "/exclusive/j20/images/0.png",
      "/exclusive/j20/images/bath1.webp",
      "/exclusive/j20/images/bed 1.webp",
      "/exclusive/j20/images/cinema.webp",
      "/exclusive/j20/images/dining formal.webp",
      "/exclusive/j20/images/gym.webp",
    ],
    featured: true,
    href: "/property/custom-built-signature-villa",
  },
  {
    id: "billionaires-row",
    title: "Billionaires Row Signature Villa",
    location: "Dubai Marina, Dubai",
    price: 150000000,
    currency: "AED",
    bedrooms: 6,
    bathrooms: 8,
    squareFootage: 12000,
    squareFootageUnit: "Sq.Ft",
    images: [
      "/exclusive/g11/images/home.png",
      "/exclusive/g11/images/1.webp",
      "/exclusive/g11/images/2.webp",
      "/exclusive/g11/images/3.webp",
      "/exclusive/g11/images/4.webp",
      "/exclusive/g11/images/5.webp",
    ],
    featured: false,
    href: "/property/luxury-villa",
  },
  {
    id: "palm-villa-456",
    title: "Custom-Built Signature Villa",
    location: "Palm Jumeirah, Dubai",
    price: 250000000,
    currency: "AED",
    bedrooms: 5,
    bathrooms: 7,
    squareFootage: 15190.3,
    squareFootageUnit: "Sq.Ft",
    images: [
      "/exclusive/j20/images/0.png",
      "/exclusive/j20/images/bath1.webp",
      "/exclusive/j20/images/bed 1.webp",
      "/exclusive/j20/images/cinema.webp",
      "/exclusive/j20/images/dining formal.webp",
      "/exclusive/j20/images/gym.webp",
    ],
    featured: true,
    href: "/property/custom-built-signature-villa",
  },
  {
    id: "billionaires-row",
    title: "Billionaires Row Signature Villa",
    location: "Dubai Marina, Dubai",
    price: 150000000,
    currency: "AED",
    bedrooms: 6,
    bathrooms: 8,
    squareFootage: 12000,
    squareFootageUnit: "Sq.Ft",
    images: [
      "/exclusive/g11/images/home.png",
      "/exclusive/g11/images/1.webp",
      "/exclusive/g11/images/2.webp",
      "/exclusive/g11/images/3.webp",
      "/exclusive/g11/images/4.webp",
      "/exclusive/g11/images/5.webp",
    ],
    featured: false,
    href: "/property/luxury-villa",
  },
  {
    id: "palm-villa-456",
    title: "Custom-Built Signature Villa",
    location: "Palm Jumeirah, Dubai",
    price: 250000000,
    currency: "AED",
    bedrooms: 5,
    bathrooms: 7,
    squareFootage: 15190.3,
    squareFootageUnit: "Sq.Ft",
    images: [
      "/exclusive/j20/images/0.png",
      "/exclusive/j20/images/bath1.webp",
      "/exclusive/j20/images/bed 1.webp",
      "/exclusive/j20/images/cinema.webp",
      "/exclusive/j20/images/dining formal.webp",
      "/exclusive/j20/images/gym.webp",
    ],
    featured: true,
    href: "/property/custom-built-signature-villa",
  },
  {
    id: "billionaires-row",
    title: "Billionaires Row Signature Villa",
    location: "Dubai Marina, Dubai",
    price: 150000000,
    currency: "AED",
    bedrooms: 6,
    bathrooms: 8,
    squareFootage: 12000,
    squareFootageUnit: "Sq.Ft",
    images: [
      "/exclusive/g11/images/home.png",
      "/exclusive/g11/images/1.webp",
      "/exclusive/g11/images/2.webp",
      "/exclusive/g11/images/3.webp",
      "/exclusive/g11/images/4.webp",
      "/exclusive/g11/images/5.webp",
    ],
    featured: false,
    href: "/property/luxury-villa",
  },
  {
    id: "palm-villa-456",
    title: "Custom-Built Signature Villa",
    location: "Palm Jumeirah, Dubai",
    price: 250000000,
    currency: "AED",
    bedrooms: 5,
    bathrooms: 7,
    squareFootage: 15190.3,
    squareFootageUnit: "Sq.Ft",
    images: [
      "/exclusive/j20/images/0.png",
      "/exclusive/j20/images/bath1.webp",
      "/exclusive/j20/images/bed 1.webp",
      "/exclusive/j20/images/cinema.webp",
      "/exclusive/j20/images/dining formal.webp",
      "/exclusive/j20/images/gym.webp",
    ],
    featured: true,
    href: "/property/custom-built-signature-villa",
  },
]


  