export const icons =[
  {label: "security", icon: "./24x7-Security.webp"},
  {label: "Ain Dubai", icon: "./Ain-Dubai.webp"},
  {label: "Basket Ball Court", icon: "./Basketball-Court.webp"},
  {label: "BBQ Area", icon: "./BBQ-Areas.webp"},
  {label: "Beach", icon: "./Beach-Access.webp"},
  {label:"Beauty Bar", icon: "./Beauty-Bar.svg"},
  {label: "Burj Al Arab", icon: "./Burj-Al-Arab.webp"},
  {label: "Burj Khalifa", icon: "./Burj-Khalifa.webp"},
  {label: "Business Bay Metro", icon: "./Business-Bay-Metro.webp"},
  {label: "Gold Course", icon: "./Championship-Golf-Course.png"},
  {label: "Children's Park", icon: "./Children-Park.webp"},
  {label: "Cinema", icon: "./cinema-screen.png"},
  {label: "Comunity Hall", icon: "./Community-Hall.webp"},
  {label: "Cycling Trails", icon: "./Cycling-Trails.webp"},
  {label: "Dining Outlets", icon: "./Dining-Outlets.webp"},
  {label: "Down Payment", icon: "./down-payment.webp"},
  {label: "DownTown", icon: "./Downtown.webp"},
  {label: "Dubai International Airport", icon: "./Dubai-International-Airport.webp"},
  {label: "Dubai International Financial Centre (DIFC)", icon: "./Dubai-Marina.webp"},
  {label: "Dubai Marina", icon: "./Dubai-Marina.webp"},
  {label: "During Construction", icon: "./during-construction.webp"},
  {label: "Fitness Centre", icon: "./Fitness-Centre.webp"},
  {label: "Floting Pods", icon: "./FLOATING-pods.svg"},
  {label: "Game Room", icon: "./Games-Room.webp"},
  {label: "Green Parks", icon: "./GREEN-PARKS.png"},
  {label: "Green Surrounding", icon: "./Green-Surrounding.webp"},
  {label: "Health Care Centre", icon: "./Health-Care-Centre.webp"},
  {label: "Hospital", icon: "./Hospital.webp"},
  {label: "House Keeping", icon: "./Housekeeping.webp"},
  {label: "Illumine Beauty Studio", icon: "./ILLUMINE-BEAUTY-STUDIO.svg"},
  {label: "Indoor Games", icon: "./Indoor-Games.webp"},
  {label: "Infinity Pool", icon: "./Infinity-Pool.webp"},
  {label: "Jogging Trials", icon: "./Jogging-Trails.webp"},
  {label: "Jumeirah Beach", icon: "./Jumeirah-Beach.webp"},
  {label: "Kids Play Area", icon: "./Kids-Play-Area.webp"},
  {label: "Kids Pool", icon: "./Kids-Pool.webp"},
  {label: "Mall of The Emrates", icon: "./Mall-of-the-Emirates.webp"},
  {label: "Marina & Yacht Club", icon: "./Marina-&-Yacht-Club.webp"},
  {label: "Mosque", icon: "./Mosque.webp"},
  {label: "Outdoor Dining Area", icon: "./Outdoor-Dining-Area.webp"},
  {label: "Outdoor Gym", icon: "./Outdoor-Gymnasium.webp"},
  {label: "Outdoor Pool", icon: "./Outdoor-Pool.webp"},
  {label: "Outdoor Sitting Area", icon: "./Outdoor-Sitting-Area.webp"},
  {label: "Park", icon: "./Park.webp"},
  {label: "Parking Facility", icon: "./Parking-Facility.webp"},
  {label: "Park Leisure Areas", icon: "./parks-leisure-areas.svg"},
  {label: "Property Location", icon: "./property-location.png"},
  {label: "Property Size", icon: "./property-sizes.png"},
  {label: "Ras Al Khor Wildlife Sanctuary", icon: "./Ras-Al-Khor-Wildlife-Sanctuary.webp"},
  {label: "Cafe", icon: "./Restaurant-Cafe.webp"},
  {label: "Restaurants", icon: "./Restaurants.webp"},
  {label: "Retail & Dining", icon: "./Retail-&-Dining-Options.webp"},
  {label: "Retail Outlets", icon: "./Retail-Outlets.webp"},
  {label: "Running Track", icon: "./Running-Track.webp"},
  {label: "School", icon: "./Schools.webp"},
  {label: "Sheikh Zayed Road", icon: "./Sheikh-Zayed-Road.webp"},
  {label: "Shopping Mall", icon: "./Shopping-Mall.webp"},
  {label: "Skating Track", icon: "./Skating-Track.webp"},
  {label: "Solar Powered", icon: "./SOLAR-POWERED-SUN-LOUNGER.svg"},
  {label: "Spa & Sauna", icon: "./Spa-and-Sauna.webp"},
  {label: "Spa", icon: "./Spa.svg"},
  {label: "Sports Court", icon: "./Sports-Court.webp"},
  {label: "Sports Facilities", icon: "./Sports-Facilities.png"},
  {label: "Starting Payment Plan", icon: "./starting-payment-plan.png"},
  {label: "Starting Price", icon: "./starting-payment-plan.png"},
  {label: "Supermarket", icon: "./Supermarket.webp"},
  {label: "Swimming Pool", icon: "./Swimming-Pool.svg"},
  {label: "Tennis Court", icon: "./Tennis-Court.webp"},
  {label: "The Dubai Mall", icon: "./The-Dubai-Mall.webp"},
  {label: "Water Activity", icon: "./Water-Activity.webp"},
  {label: "Water Features", icon: "./water-featues.png"},
  {label: "Yoga & Meditation", icon: "./Yoga-&-Meditation.webp"},
]